import londoncalling from '../images/londoncalling.png';
import liquidswords from '../images/liquidswords.jpg';
import zombie from '../images/zombie.jpeg';
import revolver from '../images/revolver.jpeg';
import zuma from '../images/zuma.jpg';
import ctrl from '../images/ctrl.jpeg';
import digyourownhole from '../images/digyourownhole.jpeg';
import ninasimoneinconcert from '../images/ninasimoneinconcert.jpeg';

export const records = [
    {
        id: 1, image: londoncalling, artist: 'The Clash', album: 'London Calling', year: 1979, genre: 'Punk', price: '24.99', description: 'London Calling is the third studio album by English rock band The Clash. It was originally released as a double album in the United Kingdom on 14 December 1979 by CBS Records, and in the United States in January 1980 by Epic Records. The Clash recorded the album at Wessex Sound Studios in London during August, September and November 1979, following a change in management and a period of writer\'s block for Joe Strummer and Mick Jones, the band\'s lead vocalists, guitarists, and lyricists. Marking a bridge between a traditional punk rock sound and a new post - punk aesthetic, London Calling reflects the band\'s growing interest in a range of styles beyond their punk roots, including reggae, rockabilly, ska, New Orleans R&B, pop, lounge jazz, and hard rock. Themes explored in the songs include social displacement, unemployment, racial conflict, drug use, and the responsibilities of adulthood.'
    },
    {
        id: 2, image: liquidswords, artist: 'GZA', album: 'Liquid Swords', year: 1995, genre: 'Rap', price: '19.99', description: 'Liquid Swords is the second solo studio album by American rapper and Wu-Tang Clan member GZA, released on November 7, 1995, by Geffen Records. Recording sessions for the album began midway through 1995 at producer RZA\'s basement studio in the New York City borough of Staten Island.The album heavily samples dialogue from the martial arts film Shogun Assassin and maintains a dark atmosphere throughout its course, while it incorporates lyrical references to chess, crime and philosophy. Liquid Swords features numerous guest appearances from the entire nine piece Wu- Tang Clan, and also Wu - Tang affiliate Killah Priest. Upon its release, Liquid Swords peaked at number nine on the Billboard 200 chart, and number two on the Top R & B / Hip - Hop Albums chart. The Recording Industry Association of America(RIAA) certified the album platinum in sales nearly 20 years after its release. Upon its initial release, Liquid Swords received critical acclaim for its complex lyricism and hypnotic musical style. Over the years, its recognition has grown, with a number of famous publishers proclaiming it as one of the greatest hip hop albums of all time. In 2007, the Chicago Tribune cited it as "one of the most substantial lyrical journeys in hip-hop history".'
    },
    {
        id: 3, image: zombie, artist: 'Fela Kuti', album: 'Zombie', year: 1976, genre: 'Afrobeat', price: '22.99', description: 'Zombie is a studio album by Nigerian Afrobeat musician Fela Kuti. It was released in Nigeria by Coconut Records in 1976, and in the United Kingdom by Creole Records in 1976. The album was a scathing attack on Nigerian soldiers using the zombie metaphor to describe the methods of the Nigerian military. The album was a smash hit with the people and infuriated the government, setting off a vicious attack against the Kalakuta Republic (a commune that Fela had established in Nigeria), during which one thousand soldiers attacked the commune. Kuti was severely beaten, and his elderly mother was thrown from a window, causing fatal injuries. The Kalakuta Republic was burned, and Kuti\'s studio, instruments, and master tapes were destroyed. Kuti claimed that he would have been killed if it were not for the intervention of a commanding officer as he was being beaten. Kuti\'s response to the attack was to deliver his mother\'s coffin to the main army barrack in Lagos and write two songs, "Coffin for Head of State" and "Unknown Soldier", referencing the official inquiry that claimed the commune had been destroyed by an unknown soldier. Kuti and his band then took residence in Crossroads Hotel as the Shrine had been destroyed along with his commune. In 1978 Kuti married 27 women, many of whom were his dancers, composers, and singers to mark the anniversary of the attack on the Kalakuta Republic. Later, he was to adopt a rotation system of keeping only twelve simultaneous wives. The year was also marked by two notorious concerts, the first in Accra in which riots broke out during the song "Zombie," which led to Kuti being banned from entering Ghana. The second was at the Berlin Jazz Festival after which most of Kuti\'s musicians deserted him, due to rumors that Kuti was planning to use the entirety of the proceeds to fund his presidential campaign.'
    },
    {
        id: 4, image: revolver, artist: 'The Beatles', album: 'Revolver', year: 1966, genre: 'Rock/Pop', price: '18.99', description: 'Revolver is the seventh studio album by the English rock band the Beatles. It was released on 5 August 1966, accompanied by the double A-side single "Eleanor Rigby" / "Yellow Submarine". The album was the Beatles\' final recording project before their retirement as live performers and marked the group\'s most overt use of studio technology to date, building on the advances of their late 1965 release Rubber Soul. It has since become regarded as one of the greatest albums in popular music, with recognition centred on its range of musical styles, diverse sounds, and lyrical content. The Beatles recorded Revolver after taking a three- month break at the start of 1966, and during a period when London was feted as the era\'s cultural capital. The songs reflect the group\'s interest in the drug LSD, Eastern philosophy and the avant - garde, lyrically addressing themes such as death and transcendence from material concerns. With no thoughts of reproducing their new material in concert, the band made liberal use of automatic double tracking, varispeed, reversed tapes, close audio miking, and instruments outside of their standard live set - up.'
    },
    {
        id: 5, image: zuma, artist: 'Neil Young & Crazy Horse', album: 'Zuma', year: 1975, genre: 'Rock', price: '20.99', description: 'Zuma is the seventh studio album by Canadian musician Neil Young, released on Reprise Records in November 1975. Co-credited to Crazy Horse, it includes "Cortez the Killer," one of Young\'s best-known songs. The death of guitarist and bandmate Danny Whitten from a drug overdose in 1972 affected Young greatly, and left the Crazy Horse band without its leader and songwriter. Young went out on tour in late 1973 with a band dubbed the Santa Monica Flyers, composed of the Crazy Horse rhythm section of bassist Billy Talbot and drummer Ralph Molina along with guitarist Nils Lofgren, who had played on Crazy Horse\'s debut album, and multi-instrumentalist Ben Keith, this group recording most of the tracks for what would be his Tonight\'s the Night album. After the 1974 stadium tour with Crosby, Stills & Nash and another abandoned attempt at the second CSNY studio album, Young formed a new version of Crazy Horse in 1975 with guitarist Frank Sampedro slotted in alongside Talbot and Molina. This line-up first appeared on this album, and remained stable until 2018 when Sampedro decided to take a break from touring and Nils Lofgren was recruited to play guitar for the live shows.'
    },
    {
        id: 6, image: ctrl, artist: 'SZA', album: 'Ctrl', year: 2017, genre: 'R&B/Soul', price: '17.99', description: 'Ctrl (pronounced "control") is the debut studio album by American singer SZA. It was released on June 9, 2017, on Top Dawg Entertainment and RCA Records. Originally scheduled for release in late 2015, it was delayed by SZA\'s experience of "a kind of blinding paralysis brought on by anxiety." She worked and reworked the album until the record company took away her hard drive in the spring of 2017. SZA wrote most of the album\'s lyrics and collaborated with producers including Craig Balmoris, Frank Dukes, Carter Lang, Scum and ThankGod4Cody to achieve its sound. The efforts resulted in a primarily neo-soul and R&B album, with elements of hip-hop, electronic, indie and soul. Lyrically the album has a confessional theme, which touch upon SZA\'s personal experiences and complexities of modern love; including desire, competition, jealousy, sexual politics, social media, and low self-esteem.'
    },
    {
        id: 7, image: digyourownhole, artist: 'The Chemical Brothers', album: 'Dig Your Own Hole', year: 1997, genre: 'Electronic', price: '21.99', description: 'Dig Your Own Hole is the second studio album by English electronic music duo the Chemical Brothers. It was released on 7 April 1997 in the United Kingdom by Freestyle Dust and Virgin Records and in the United States by Astralwerks. The album was recorded between 1995 and 1997, and features Noel Gallagher of Oasis and Beth Orton as guest vocalists. The album became the duo\'s first to peak at number one in the UK, achieving this peak in April 1997. Five singles were released from the album, two of which reached number one in the UK: "Setting Sun", "Where Do I Begin", "Block Rockin\' Beats", "Elektrobank", and "The Private Psychedelic Reel". The album has been included in several British magazines\' lists of the best albums ever. The success of the album led The Chemical Brothers to be much sought-after remixers, and the duo released a mix album in 1998 titled Brothers Gonna Work It Out.'
    },
    {
        id: 8, image: ninasimoneinconcert, artist: 'Nina Simone', album: 'Nina Simone in Concert', year: 1964, genre: 'Jazz', price: '25.99', description: 'Nina Simone in Concert is an album by jazz singer Nina Simone. It was her first album for the record label Philips and consisted of three live recordings made at Carnegie Hall, New York City, in March and April 1964. She recorded Nina Simone at Carnegie Hall in 1963 for Colpix. This album marked the beginning of "Nina Simone, the Civil Rights singer" in her recording career; she had already incorporated the civil rights message in her performances. Included on the album are political songs, such as "Mississippi Goddam", released as a single at the time. "Old Jim Crow", "Go Limp" "Pirate Jenny" contributed to the message in a covert or metaphorical way. The album was rated 94th best album of the 1960s by Pitchfork.'
    }
];